name: Terratest

on:
  push:
    branches: 
      - "*" 
  pull_request:
    branches: 
      - "*"

jobs:

  terratest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Init
      run: go mod init "./test/ec2_test.go"
    
    - name: Tidy
      run: go mod tidy


    - name: Test
      run: go test -v ./test/url_parser_test.go