# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Terratest

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  terratest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Test
      run: cd test && go test -v ./test/url_parser_test.go
